package cn.zno.pojo;

public class Foo {
	public Foo() {
	}

	public Foo(String name) {
		this.name = name;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column FOO.ID
	 *
	 * @mbggenerated
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column FOO.NAME
	 *
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column FOO.ID
	 *
	 * @return the value of FOO.ID
	 *
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column FOO.ID
	 *
	 * @param id
	 *            the value for FOO.ID
	 *
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column FOO.NAME
	 *
	 * @return the value of FOO.NAME
	 *
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column FOO.NAME
	 *
	 * @param name
	 *            the value for FOO.NAME
	 *
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}