package cn.zno.pojo;

import java.math.BigDecimal;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.AGE
     *
     * @mbggenerated
     */
    private BigDecimal age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.ID
     *
     * @return the value of PERSON.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.ID
     *
     * @param id the value for PERSON.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.NAME
     *
     * @return the value of PERSON.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.NAME
     *
     * @param name the value for PERSON.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.AGE
     *
     * @return the value of PERSON.AGE
     *
     * @mbggenerated
     */
    public BigDecimal getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.AGE
     *
     * @param age the value for PERSON.AGE
     *
     * @mbggenerated
     */
    public void setAge(BigDecimal age) {
        this.age = age;
    }

	@Override
	public String toString() {
		return "Person [id=" + id + ", name=" + name + ", age=" + age + "]";
	}
}