package cn.zno.dao;

import cn.zno.pojo.Foo;
import cn.zno.pojo.FooExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FooMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbggenerated
     */
    int countByExample(FooExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbggenerated
     */
    int deleteByExample(FooExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbggenerated
     */
    int insert(Foo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbggenerated
     */
    int insertSelective(Foo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbggenerated
     */
    List<Foo> selectByExample(FooExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Foo record, @Param("example") FooExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Foo record, @Param("example") FooExample example);
}